### ISSUE TITLE
Unable to get token back. 

### ISSUE THREAD

**Issue by shotah** [LawrenceHwang/OktaAWSToken#1]
After checking the config I saw account was spelled acoount. Fixed that, now getting the following error. I would really like to see this work. :)

`GetSAML: Error during authenticating with given username/ password.
At C:\Users\%username%\Documents\WindowsPowerShell\Modules\OktaAWSToken\OktaAWSToken.psm
1:168 char:19
+   $SamlResponse = GetSAML
+                   ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,GetSAM 
`

**Comment by shotah** [comment]
I'm also not getting a prompt for MFA. I wanted to enable Google MFA.

**Comment by LawrenceHwang** [comment]
Hello @shotah,

How are you making out on the issue? I am unable to validate it because I don't have access to Okta anymore. I'd be happy to help out where I can so do feel free to let me know.

Thanks,

Lawrence

**Comment by etendards** [comment]
Has anyone found a working script to make Okta AWS CLI integration work ?

**Comment by LawrenceHwang** [comment]
@etendards  You can look at the saml2aws project. https://github.com/Versent/saml2aws

**Comment by bmorgan42175** [comment]
@shotah 

I ran into the same GetSAML error that you reference above and was able to resolve it by placing the following line in my powershell profile to force my current console to use TLS 1.2

[Net.ServicePointManager]::SecurityProtocol  = [Net.SecurityProtocolType]::Tls12

**Comment by LawrenceHwang** [comment]
Thank you @bmorgan42175 for sharing the info. I might be able to get that fix into the next release.

**Comment by aman-bains11** [comment]
Do we need to add this line ([Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12)at the start of the GETSAML function , please confirm as I am bit struck at the Select the Role verbose and on selecting a value it keeps on asking and its not populating the arn (arn:aws:iam::289989777888:saml-provider/Okta_IdP) . Any help would be really appreciated

**Comment by bmorgan42175** [comment]
I would just put that line in your powershell profile so it loads up when you launch your powershell console.  If you dont want to do that then I would probably put it on line 35 of the OktaAWSToken.psm1 file, so yes essentially at the start of the GetSAML function
